<?php


class AllNav extends NavExtension
{
    public static function displayHeader($title)
    {
        parent::displayHeader($title); // TODO: Change the autogenerated stub
        ?>
        <script>
            //the media type
            var media = "all";

        </script>
        <?php
    }

    public static function displayFooter()
    {
        parent::displayFooter(); // TODO: Change the autogenerated stub
    }

}